version: "3.8"
services:
  api-server:
    build:
      context: ./api-server/src
      dockerfile: Dockerfile
    container_name: api-server
    image: manojreddy9/automobile
    restart: always
    tty: true
    ports:
      - 5000:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge