version: "3.8"
services:
  api-server:
    build:
      context: ./api-server/src
      dockerfile: Dockerfile.dev
    container_name: api-server
    volumes:
      - ./api-server/src:/src
    image: backend
    restart: always
    tty: true
    ports:
      - 5000:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge